name: Coverage
on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update pip
        run: |
          pip install -U wheel
          pip install -U setuptools
          python -m pip install -U pip
      - run: pip install tox coverage
      - name: combine coverage
        run: |
          python -m coverage erase
          tox -c tox_cov.ini
          python -m coverage combine
          python -m coverage report --fail-under=98
